@echo off
echo 正在启动手机数据可视化系统...
echo 正在编译项目...
call mvn clean package -DskipTests
echo 正在启动服务...
start /B java -jar target/spider-1.0-SNAPSHOT.jar
echo 等待服务启动...
timeout /t 10 /nobreak
echo 正在打开浏览器...
start http://localhost:8080 